### ISSUE TITLE
封面排版的建议

### ISSUE THREAD

**Issue by Happy-Rabbit-YY** [nuisttudou/NUIST_thesis_template_change#1]
学长好！

在排版封面的时候，比如对
指导教师
班    级
姓    名
专业年级
这个排版的时候，在考虑要不要用`tabular`的形式来排版，比如
```LaTeX
\let\kaishu\relax
\setCJKfamilyfont\kaishu{KaiTi}[AutoFakeBold]
\usepackage{array}

\begin{tabular}[>{\kaishu \bfseries}l>{\kaishu \bfseries}r@{：}c]
指导 & 教师 & \myteachername \\
班 & 级 & \myclass \\
姓 & 名 & \myname \\
专业 & 年级 & \thevar
\end{tabular}
```
这个样子（？）

比如| 这个 | 样子| 但没有竖线
:--|--:|:-:|:-:
指导 | 教师 |：| \myteachername
班  |级 |：| \myclass 
姓  |名 |：| \myname 
专业 | 年级 | ：| \thevar

只是一个小想法，在看了[`ucasthesis`](https://github.com/mohuangrui/ucasthesis)模板后想到的。
（我因为是个菜比，所以我的毕设论文是根据`ucasthesis`修改的（指复制粘贴修修补补））

这个是我根据`ucasthesis`模板修改后生成的封面，作者姓名等基本信息那里，看上去会更好一些（？）
![IMG_20220409_011100.jpg](https://user-images.githubusercontent.com/101640429/162489912-a176430e-416c-4e2b-8771-7295bc74215d.jpg)

或者使用`\makebox`的方式？试着做了一下小测试，下面是测试的代码，以及生成pdf的样式
```LaTeX
\documentclass[UTF8,a4paper]{ctexart}

\usepackage{ulem}

\newcommand{\tbul}[1]{\uline{\makebox[18em][c]{#1}}}
\newcommand{\tbhd}[1]{\makebox[5em][s]{#1}}

\begin{document}
    \begin{tabular*}{\textwidth}[htb!]{p{5em}@{:}c}
        \tbhd{作者姓名} & \tbul{aaa} \\
        \tbhd{指导教师} & \tbul{bbb} \\
        \tbhd{院系} & \tbul{ccc} \\
        \tbhd{身份证} & \tbul{ddd}
    \end{tabular*}
\end{document}

```
![Screenshot_2022-04-09-02-47-23-487_com.adobe.reader.jpg](https://user-images.githubusercontent.com/101640429/162503473-5de3c26e-6293-4450-856e-939890d65c1b.jpg)

**Comment by Happy-Rabbit-YY** [comment]
这个是我根据`ucasthesis`的模板修改后的封面，列表是对齐了的
![Screenshot_2022-04-08-04-06-52-055_com.tencent.mobileqq-01.jpeg](https://user-images.githubusercontent.com/101640429/162287545-7cea8e66-1371-4094-86b7-a63bb9dafe5c.jpeg)

**Comment by nuisttudou** [comment]
你好呀，很高兴毕业以后还能在这里看到母校来的消息！感谢你的issue建议，我会在Readme里面提醒大家可以看一下你的issue的建议。因已毕业，这份模板可能会比较old了，所以可以参考https://github.com/sakronos/NUIST_Bachelor_Thesis_LaTeX_Template 这个，我看是2022年更新的，应该比较ok。我看到你已Star了它。顺祝毕业顺利。

**Comment by Happy-Rabbit-YY** [comment]
好的学长，谢谢你的建议！我去参考一下。
